[package]
name = "aoc-day-1"
version = "0.1.0"
edition = "2021"

[dependencies]
acton-reactive = "3.0.0-beta.2"
futures = "0.3.31"
tokio = { version = "1.41.1", features = ["full"] }

[dev-dependencies]
acton_test = "1.1.4"
