[package]
name = "aoc-day-7"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"
memory-stats = "1.2.0"


[[bench]]
name = "bridge_benches"
harness = false
