[package]
name = "aoc-day-7"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
memory-stats = "1.2.0"

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "bridge_benches"
harness = false

[[bin]]
name = "memprofile"
path = "src/bin/memprofile.rs"
